"""
art.py — parametric SVG product illustrations for the MABEL Robotics store.

Every product figure on the site is generated by this module. Nothing is drawn
by hand and nothing is a photograph, so the whole catalogue shares one lighting
model, one material vocabulary and one camera.

Camera      three-quarter-ish, slightly above the part, orthographic.
Key light   upper-left, 35 deg. Fill from the lower-right at ~18% strength.
Ground      one soft contact ellipse; the art is otherwise transparent so it
            sits on white or on the #f5f5f7 band without a seam.
Canvas      1000 x 1000 user units, the subject inside a 720 unit safe box.
"""

from __future__ import annotations
import math

W = H = 1000.0
CX = 500.0

# ---------------------------------------------------------------- materials --
# Each material is a 5-stop ramp read as: deep shadow, shadow, body, light,
# specular. Renderers pick stops rather than naming colours, so re-lighting the
# whole catalogue is one edit here.
MATERIALS = {
    "alu":        ["#8d939c", "#b3b9c1", "#d6dade", "#eef0f2", "#ffffff"],
    "alu_dark":   ["#4a4f56", "#6b7078", "#8f959d", "#b8bdc4", "#e6e9ec"],
    "anod_black": ["#141619", "#25282d", "#3a3e45", "#565b64", "#8c929c"],
    "anod_grey":  ["#2f333a", "#454a53", "#606670", "#828994", "#b7bec8"],
    "anod_red":   ["#6d1410", "#992018", "#c62f22", "#e05a44", "#f3a494"],
    "anod_blue":  ["#0d3358", "#14497c", "#1c66a8", "#3f8fd0", "#8fc4ea"],
    "anod_gold":  ["#6b4a12", "#96691b", "#c08c28", "#dcb055", "#f2dca3"],
    "steel":      ["#5c6168", "#7d838b", "#a5abb3", "#ccd1d6", "#f2f4f6"],
    "copper":     ["#6e3417", "#95491f", "#bc6430", "#d98a56", "#f0bb96"],
    "plastic_wh": ["#b8bcc2", "#d3d7dc", "#e9ecef", "#f7f8fa", "#ffffff"],
    "plastic_bk": ["#0e0f11", "#1b1d20", "#2b2e33", "#414449", "#6d727a"],
    "pcb_green":  ["#0a2a18", "#0f3f22", "#166030", "#238a45", "#4fbe73"],
    "pcb_blue":   ["#0a1f3a", "#102f56", "#17457c", "#2665ad", "#4f92d8"],
    "pcb_black":  ["#0b0d10", "#141719", "#1f2327", "#2e3339", "#4b525a"],
    "glass":      ["#0a1014", "#12202a", "#1d3947", "#2f6076", "#7fb6cc"],
    "rubber":     ["#0b0c0d", "#141618", "#1f2225", "#2e3236", "#4a4f55"],
    "silicone":   ["#8a3b52", "#b04d69", "#cf6683", "#e492a7", "#f6ccd7"],
    "brass":      ["#7a5a12", "#a3781c", "#c99a2e", "#e0bb60", "#f4e0a8"],
    "carbon":     ["#0d0e10", "#17191c", "#232629", "#33373c", "#5b6169"],
}


def mat(name: str) -> list[str]:
    return MATERIALS.get(name, MATERIALS["alu"])


# ------------------------------------------------------------------- canvas --
class Art:
    """Collects defs and body so gradients get unique ids per figure."""

    def __init__(self, pid: str):
        self.pid = pid.replace("/", "-")
        self.defs: list[str] = []
        self.body: list[str] = []
        self._n = 0

    def uid(self, tag: str) -> str:
        self._n += 1
        return f"{self.pid}-{tag}-{self._n}"

    def add(self, s: str) -> None:
        self.body.append(s)

    def define(self, s: str) -> None:
        self.defs.append(s)

    # -- gradients ---------------------------------------------------------
    def lin(self, stops, x1=0.0, y1=0.0, x2=1.0, y2=0.0, tag="lg") -> str:
        gid = self.uid(tag)
        st = "".join(
            f'<stop offset="{o:.4f}" stop-color="{c}"'
            + (f' stop-opacity="{a}"' if a is not None else "")
            + "/>"
            for o, c, a in stops
        )
        self.define(
            f'<linearGradient id="{gid}" x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}">{st}</linearGradient>'
        )
        return gid

    def rad(self, stops, cx=0.5, cy=0.5, r=0.5, fx=None, fy=None, tag="rg") -> str:
        gid = self.uid(tag)
        f = f' fx="{fx}" fy="{fy}"' if fx is not None else ""
        st = "".join(
            f'<stop offset="{o:.4f}" stop-color="{c}"'
            + (f' stop-opacity="{a}"' if a is not None else "")
            + "/>"
            for o, c, a in stops
        )
        self.define(
            f'<radialGradient id="{gid}" cx="{cx}" cy="{cy}" r="{r}"{f}>{st}</radialGradient>'
        )
        return gid

    def blur(self, px: float) -> str:
        fid = self.uid("bl")
        self.define(
            f'<filter id="{fid}" x="-60%" y="-60%" width="220%" height="220%">'
            f'<feGaussianBlur stdDeviation="{px}"/></filter>'
        )
        return fid

    # Subjects are composed around (500, 520); this zoom makes them fill the
    # frame like a product shot instead of floating in white space.
    ZOOM = 1.15
    PIVOT = (500.0, 520.0)

    def render(self, title: str) -> str:
        px, py = self.PIVOT
        z = self.ZOOM
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W:.0f} {H:.0f}" '
            f'role="img" aria-label="{esc(title)}" preserveAspectRatio="xMidYMid meet">'
            f"<title>{esc(title)}</title>"
            f"<defs>{''.join(self.defs)}</defs>"
            f'<g transform="translate({px:.1f} {py:.1f}) scale({z}) translate({-px:.1f} {-py:.1f})">'
            f"{''.join(self.body)}"
            "</g></svg>"
        )


def esc(s: str) -> str:
    return (
        str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


# ---------------------------------------------------------------- primitives --
def ground(a: Art, cx: float, cy: float, rx: float, ry: float, op=0.20) -> None:
    """One soft contact shadow. Always the first thing drawn."""
    g = a.rad(
        [(0.0, "#0b0f14", op), (0.55, "#0b0f14", op * 0.45), (1.0, "#0b0f14", 0.0)],
        tag="gnd",
    )
    f = a.blur(rx * 0.055)
    a.add(f'<ellipse cx="{cx:.1f}" cy="{cy:.1f}" rx="{rx:.1f}" ry="{ry:.1f}" fill="url(#{g})" filter="url(#{f})"/>')


def body_ramp(a: Art, m: list[str], horizontal=True, tag="body") -> str:
    """The standard curved-surface ramp: key light from the upper-left."""
    stops = [
        (0.00, m[1], None),
        (0.10, m[2], None),
        (0.26, m[3], None),
        (0.34, m[4], None),
        (0.42, m[3], None),
        (0.62, m[2], None),
        (0.86, m[1], None),
        (1.00, m[0], None),
    ]
    if horizontal:
        return a.lin(stops, 0, 0, 1, 0, tag=tag)
    return a.lin(stops, 0, 0, 0, 1, tag=tag)


def cap_ramp(a: Art, m: list[str], tag="cap") -> str:
    """Top face of a cylinder — light pools upper-left, falls to the far rim."""
    return a.rad(
        [(0.0, m[4], None), (0.34, m[3], None), (0.72, m[2], None), (1.0, m[1], None)],
        cx=0.36, cy=0.30, r=0.78, tag=tag,
    )


def cylinder(a: Art, cx: float, top: float, d: float, h: float, m: list[str],
             squash=0.26, cap=True, rim=True) -> dict:
    """Upright cylinder seen slightly from above. Returns key geometry."""
    r = d / 2.0
    ry = r * squash
    bot = top + h
    grad = body_ramp(a, m)
    # side wall
    a.add(
        f'<path d="M {cx-r:.1f} {top:.1f} L {cx-r:.1f} {bot:.1f} '
        f'A {r:.1f} {ry:.1f} 0 0 0 {cx+r:.1f} {bot:.1f} '
        f'L {cx+r:.1f} {top:.1f} Z" fill="url(#{grad})"/>'
    )
    # bottom shade
    sh = a.lin([(0, "#000", 0.0), (1, "#000", 0.30)], 0, 0, 0, 1, tag="bsh")
    a.add(
        f'<path d="M {cx-r:.1f} {bot-h*0.30:.1f} L {cx-r:.1f} {bot:.1f} '
        f'A {r:.1f} {ry:.1f} 0 0 0 {cx+r:.1f} {bot:.1f} '
        f'L {cx+r:.1f} {bot-h*0.30:.1f} Z" fill="url(#{sh})"/>'
    )
    if cap:
        cg = cap_ramp(a, m)
        a.add(f'<ellipse cx="{cx:.1f}" cy="{top:.1f}" rx="{r:.1f}" ry="{ry:.1f}" fill="url(#{cg})"/>')
    if rim:
        a.add(
            f'<ellipse cx="{cx:.1f}" cy="{top:.1f}" rx="{r:.1f}" ry="{ry:.1f}" '
            f'fill="none" stroke="{m[4]}" stroke-opacity="0.55" stroke-width="1.6"/>'
        )
    return {"cx": cx, "top": top, "bot": bot, "r": r, "ry": ry}


def ring(a: Art, cx: float, cy: float, r: float, ry: float, t: float, m: list[str], op=1.0) -> None:
    """A band around a cylinder — anodised collar, bearing race, encoder ring."""
    g = body_ramp(a, m, tag="ring")
    a.add(
        f'<path d="M {cx-r:.1f} {cy:.1f} L {cx-r:.1f} {cy+t:.1f} '
        f'A {r:.1f} {ry:.1f} 0 0 0 {cx+r:.1f} {cy+t:.1f} '
        f'L {cx+r:.1f} {cy:.1f} A {r:.1f} {ry:.1f} 0 0 1 {cx-r:.1f} {cy:.1f} Z" '
        f'fill="url(#{g})" opacity="{op}"/>'
    )


def disc(a: Art, cx: float, cy: float, r: float, ry: float, m: list[str], inset=0.0) -> None:
    g = cap_ramp(a, m, tag="disc")
    a.add(f'<ellipse cx="{cx:.1f}" cy="{cy:.1f}" rx="{r:.1f}" ry="{ry:.1f}" fill="url(#{g})"/>')


def bolt_circle(a: Art, cx: float, cy: float, r: float, ry: float, n: int, br=7.0,
                m=None, start=0.0) -> None:
    """Counter-bored fastener holes on an ellipse — the detail that reads 'flange'."""
    m = m or mat("steel")
    for i in range(n):
        th = start + 2 * math.pi * i / n
        x = cx + r * math.cos(th)
        y = cy + ry * math.sin(th)
        a.add(f'<ellipse cx="{x:.1f}" cy="{y:.1f}" rx="{br:.1f}" ry="{br*0.62:.1f}" fill="{m[0]}" opacity="0.85"/>')
        a.add(f'<ellipse cx="{x:.1f}" cy="{y-1.2:.1f}" rx="{br*0.66:.1f}" ry="{br*0.40:.1f}" fill="#05070a" opacity="0.75"/>')


def screw_head(a: Art, x: float, y: float, r: float, m=None, kind="hex") -> None:
    m = m or mat("steel")
    g = a.rad([(0, m[4], None), (0.5, m[3], None), (1, m[1], None)], cx=0.38, cy=0.34, r=0.72, tag="sc")
    a.add(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}" fill="url(#{g})"/>')
    a.add(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}" fill="none" stroke="{m[0]}" stroke-opacity=".55" stroke-width="{r*0.14:.2f}"/>')
    if kind == "hex":
        pts = " ".join(
            f"{x + r*0.52*math.cos(math.pi/6 + k*math.pi/3):.1f},{y + r*0.52*math.sin(math.pi/6 + k*math.pi/3):.1f}"
            for k in range(6)
        )
        a.add(f'<polygon points="{pts}" fill="#0a0d11" opacity="0.82"/>')
    else:
        a.add(f'<rect x="{x-r*0.58:.1f}" y="{y-r*0.12:.1f}" width="{r*1.16:.1f}" height="{r*0.24:.1f}" rx="{r*0.06:.1f}" fill="#0a0d11" opacity="0.8"/>')


def spec_sheen(a: Art, x: float, y: float, w: float, h: float, rx=0.0, op=0.30, angle=0.0) -> None:
    """A soft diagonal specular wipe laid over a face."""
    g = a.lin(
        [(0.0, "#ffffff", 0.0), (0.38, "#ffffff", op), (0.52, "#ffffff", op * 0.5), (1.0, "#ffffff", 0.0)],
        0, 0, 1, 1, tag="sheen",
    )
    tr = f' transform="rotate({angle} {x+w/2:.1f} {y+h/2:.1f})"' if angle else ""
    a.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="{rx:.1f}" fill="url(#{g})"{tr}/>')


def edge_light(a: Art, d: str, m: list[str], w=1.8, op=0.7) -> None:
    a.add(f'<path d="{d}" fill="none" stroke="{m[4]}" stroke-opacity="{op}" stroke-width="{w}" stroke-linecap="round"/>')


def box3d(a: Art, x: float, y: float, w: float, h: float, depth: float, m: list[str],
          rx=10.0, skew=0.52) -> dict:
    """Front-facing box with a visible top and right face. depth is in y units."""
    dx = depth * skew
    dy = -depth * 0.58
    top = f"M {x:.1f} {y:.1f} L {x+dx:.1f} {y+dy:.1f} L {x+w+dx:.1f} {y+dy:.1f} L {x+w:.1f} {y:.1f} Z"
    side = f"M {x+w:.1f} {y:.1f} L {x+w+dx:.1f} {y+dy:.1f} L {x+w+dx:.1f} {y+dy+h:.1f} L {x+w:.1f} {y+h:.1f} Z"
    gt = a.lin([(0, m[4], None), (1, m[3], None)], 0, 0, 0.4, 1, tag="top")
    gs = a.lin([(0, m[1], None), (1, m[0], None)], 0, 0, 1, 0.2, tag="side")
    gf = a.lin([(0, m[3], None), (0.45, m[2], None), (1, m[1], None)], 0, 0, 0.35, 1, tag="face")
    a.add(f'<path d="{top}" fill="url(#{gt})"/>')
    a.add(f'<path d="{side}" fill="url(#{gs})"/>')
    a.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="{rx:.1f}" fill="url(#{gf})"/>')
    edge_light(a, f"M {x+rx:.1f} {y:.1f} L {x+w-rx:.1f} {y:.1f}", m, 2.0, 0.55)
    return {"fx": x, "fy": y, "fw": w, "fh": h, "dx": dx, "dy": dy}


def cable(a: Art, pts: list[tuple[float, float]], w=13.0, m=None, sleeve=True) -> None:
    """A drooping cable drawn as a smooth polyline with a highlight core."""
    m = m or mat("plastic_bk")
    d = f"M {pts[0][0]:.1f} {pts[0][1]:.1f}"
    for i in range(1, len(pts)):
        px, py = pts[i - 1]
        x, y = pts[i]
        cx1, cy1 = px + (x - px) * 0.45, py + (y - py) * 0.10
        cx2, cy2 = px + (x - px) * 0.55, py + (y - py) * 0.90
        d += f" C {cx1:.1f} {cy1:.1f} {cx2:.1f} {cy2:.1f} {x:.1f} {y:.1f}"
    a.add(f'<path d="{d}" fill="none" stroke="{m[0]}" stroke-width="{w:.1f}" stroke-linecap="round"/>')
    a.add(f'<path d="{d}" fill="none" stroke="{m[2]}" stroke-width="{w*0.66:.1f}" stroke-linecap="round"/>')
    a.add(f'<path d="{d}" fill="none" stroke="{m[4]}" stroke-opacity="0.45" stroke-width="{w*0.20:.1f}" '
          f'stroke-linecap="round" transform="translate({-w*0.16:.1f},{-w*0.18:.1f})"/>')


# =========================================================== product families =
# Each renderer takes (Art, opts) and draws one part centred in the canvas.
# opts keys are documented per family; every one falls back to a sane default.

def f_joint_module(a: Art, o: dict) -> None:
    """DAMIAO / generic integrated BLDC joint module: stator can, anodised
    collar, output flange with a bolt circle, and a rear cable gland."""
    body = mat(o.get("body", "anod_black"))
    accent = mat(o.get("accent", "anod_red"))
    d = o.get("d", 380.0)
    h = o.get("h", 250.0)
    top = 500 - h / 2 - 40
    ground(a, CX, top + h + 62, d * 0.62, d * 0.15)

    # rear housing (driver box) peeking below
    if o.get("driver", True):
        dw, dh = d * 0.78, h * 0.30
        box3d(a, CX - dw / 2, top + h - dh * 0.15, dw, dh, 40, mat("anod_grey"), rx=10)

    cyl = cylinder(a, CX, top, d, h, body)
    # anodised collar 1/3 down
    ring(a, CX, top + h * 0.36, cyl["r"], cyl["ry"], h * 0.115, accent)
    # cooling fins
    fin = a.lin([(0, "#000", 0.0), (0.5, "#000", 0.22), (1, "#000", 0.0)], 0, 0, 0, 1, tag="fin")
    for i in range(9):
        fx = CX - cyl["r"] + 16 + i * (d - 32) / 8.0
        a.add(f'<rect x="{fx:.1f}" y="{top + h*0.55:.1f}" width="4" height="{h*0.30:.1f}" fill="url(#{fin})"/>')
    # output flange on top
    fr = cyl["r"] * 0.74
    disc(a, CX, top, fr, fr * 0.26, mat("alu"))
    a.add(f'<ellipse cx="{CX:.1f}" cy="{top:.1f}" rx="{fr:.1f}" ry="{fr*0.26:.1f}" fill="none" stroke="{body[0]}" stroke-opacity=".45" stroke-width="2"/>')
    bolt_circle(a, CX, top, fr * 0.62, fr * 0.62 * 0.26, o.get("bolts", 6), br=fr * 0.075, m=mat("alu_dark"))
    # centre bore
    hr = fr * 0.24
    a.add(f'<ellipse cx="{CX:.1f}" cy="{top:.1f}" rx="{hr:.1f}" ry="{hr*0.26:.1f}" fill="#0a0d11" opacity=".9"/>')
    spec_sheen(a, CX - d * 0.42, top + h * 0.10, d * 0.20, h * 0.72, rx=10, op=0.22)
    # cable gland + pigtail
    if o.get("cable", True):
        gx = CX + cyl["r"] * 0.72
        gy = top + h * 0.74
        a.add(f'<rect x="{gx:.1f}" y="{gy:.1f}" width="30" height="26" rx="7" fill="{mat("anod_grey")[1]}"/>')
        cable(a, [(gx + 28, gy + 13), (gx + 92, gy + 34), (gx + 118, gy + 96)], 12)


def f_harmonic_joint(a: Art, o: dict) -> None:
    """EYou PHU-class harmonic joint: wide, shallow, hollow bore, CANopen."""
    body = mat(o.get("body", "anod_black"))
    d = o.get("d", 470.0)
    h = o.get("h", 175.0)
    top = 500 - h / 2 - 10
    ground(a, CX, top + h + 58, d * 0.60, d * 0.13)
    cyl = cylinder(a, CX, top, d, h, body)
    ring(a, CX, top + h * 0.62, cyl["r"], cyl["ry"], h * 0.14, mat("alu_dark"))
    fr = cyl["r"] * 0.86
    disc(a, CX, top, fr, fr * 0.26, mat("alu"))
    bolt_circle(a, CX, top, fr * 0.72, fr * 0.72 * 0.26, 12, br=fr * 0.055, m=mat("alu_dark"))
    # large hollow bore — the defining feature
    hr = fr * 0.42
    a.add(f'<ellipse cx="{CX:.1f}" cy="{top:.1f}" rx="{hr:.1f}" ry="{hr*0.26:.1f}" fill="#080a0d"/>')
    a.add(f'<ellipse cx="{CX:.1f}" cy="{top+3:.1f}" rx="{hr*0.94:.1f}" ry="{hr*0.24:.1f}" fill="none" stroke="{body[3]}" stroke-opacity=".5" stroke-width="2.5"/>')
    spec_sheen(a, CX - d * 0.40, top + h * 0.14, d * 0.18, h * 0.66, rx=8, op=0.20)


def f_pancake(a: Art, o: dict) -> None:
    """Unitree-style quasi-direct-drive: flat can with an output arm/pulley."""
    body = mat(o.get("body", "alu_dark"))
    d = o.get("d", 400.0)
    h = o.get("h", 130.0)
    top = 500 - h / 2 - 20
    ground(a, CX, top + h + 54, d * 0.60, d * 0.13)
    cyl = cylinder(a, CX, top, d, h, body)
    ring(a, CX, top + h * 0.50, cyl["r"], cyl["ry"], h * 0.16, mat("anod_black"))
    disc(a, CX, top, cyl["r"] * 0.80, cyl["r"] * 0.80 * 0.26, mat("alu"))
    bolt_circle(a, CX, top, cyl["r"] * 0.56, cyl["r"] * 0.56 * 0.26, 8, br=11, m=mat("alu_dark"))
    # output shaft with flat
    sh = cyl["r"] * 0.17
    a.add(f'<ellipse cx="{CX:.1f}" cy="{top-16:.1f}" rx="{sh:.1f}" ry="{sh*0.30:.1f}" fill="{mat("steel")[3]}"/>')
    a.add(f'<rect x="{CX-sh:.1f}" y="{top-16:.1f}" width="{sh*2:.1f}" height="16" fill="{mat("steel")[2]}"/>')
    spec_sheen(a, CX - d * 0.40, top + h * 0.12, d * 0.16, h * 0.70, rx=8, op=0.24)
    if o.get("cable", True):
        cable(a, [(CX + cyl["r"] * 0.78, top + h * 0.70), (CX + d * 0.66, top + h + 26), (CX + d * 0.60, top + h + 118)], 12)


def f_micro_motor(a: Art, o: dict) -> None:
    """Xiaomi CyberGear class: compact white/silver micro joint actuator."""
    body = mat(o.get("body", "plastic_wh"))
    d = o.get("d", 330.0)
    h = o.get("h", 190.0)
    top = 500 - h / 2 - 10
    ground(a, CX, top + h + 52, d * 0.60, d * 0.14)
    cyl = cylinder(a, CX, top, d, h, body)
    ring(a, CX, top + h * 0.58, cyl["r"], cyl["ry"], h * 0.13, mat("alu_dark"))
    disc(a, CX, top, cyl["r"] * 0.78, cyl["r"] * 0.78 * 0.26, mat("alu"))
    bolt_circle(a, CX, top, cyl["r"] * 0.54, cyl["r"] * 0.54 * 0.26, 6, br=9, m=mat("alu_dark"))
    a.add(f'<ellipse cx="{CX:.1f}" cy="{top:.1f}" rx="{cyl["r"]*0.20:.1f}" ry="{cyl["r"]*0.20*0.26:.1f}" fill="#0d1014" opacity=".9"/>')
    spec_sheen(a, CX - d * 0.40, top + h * 0.10, d * 0.18, h * 0.74, rx=8, op=0.34)
    cable(a, [(CX + cyl["r"] * 0.70, top + h * 0.78), (CX + d * 0.62, top + h + 30), (CX + d * 0.54, top + h + 112)], 11)


def f_bus_servo(a: Art, o: dict) -> None:
    """Feetech / Dynamixel smart servo: case, output horn, bus ports."""
    body = mat(o.get("body", "anod_grey"))
    w = o.get("w", 300.0)
    h = o.get("h", 420.0)
    x, y = CX - w / 2, 500 - h / 2 - 10
    ground(a, CX, y + h + 46, w * 0.72, w * 0.16)
    box3d(a, x, y, w, h, 92, body, rx=16)
    # gearbox cap
    cap = mat("alu")
    gc = a.lin([(0, cap[4], None), (0.5, cap[3], None), (1, cap[1], None)], 0, 0, 0.4, 1, tag="gc")
    a.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h*0.30:.1f}" rx="16" fill="url(#{gc})"/>')
    # output horn
    hx, hy = CX, y + h * 0.16
    a.add(f'<circle cx="{hx:.1f}" cy="{hy:.1f}" r="{w*0.24:.1f}" fill="{mat("alu_dark")[2]}"/>')
    a.add(f'<circle cx="{hx:.1f}" cy="{hy:.1f}" r="{w*0.185:.1f}" fill="{mat("alu")[3]}"/>')
    for i in range(12):
        th = 2 * math.pi * i / 12
        a.add(f'<circle cx="{hx + w*0.145*math.cos(th):.1f}" cy="{hy + w*0.145*math.sin(th):.1f}" r="{w*0.017:.1f}" fill="#0a0d11" opacity=".8"/>')
    screw_head(a, hx, hy, w * 0.05, mat("steel"))
    # bus ports
    for i, py in enumerate((y + h * 0.60, y + h * 0.74)):
        a.add(f'<rect x="{x + w*0.20:.1f}" y="{py:.1f}" width="{w*0.60:.1f}" height="{h*0.075:.1f}" rx="5" fill="#0b0e12" opacity=".85"/>')
        a.add(f'<rect x="{x + w*0.22:.1f}" y="{py+3:.1f}" width="{w*0.56:.1f}" height="{h*0.030:.1f}" rx="3" fill="{body[4]}" opacity=".22"/>')
    # mounting ears
    for ex in (x - 22, x + w + 2):
        a.add(f'<rect x="{ex:.1f}" y="{y + h*0.34:.1f}" width="20" height="{h*0.30:.1f}" rx="6" fill="{body[1]}"/>')
    spec_sheen(a, x + w * 0.06, y + h * 0.06, w * 0.22, h * 0.84, rx=12, op=0.26)
    if o.get("label"):
        a.add(f'<text x="{CX:.1f}" y="{y + h*0.92:.1f}" text-anchor="middle" '
              f'font-family="Helvetica,Arial,sans-serif" font-size="{w*0.10:.0f}" font-weight="600" '
              f'fill="{body[4]}" fill-opacity=".55" letter-spacing="1.5">{esc(o["label"])}</text>')




def f_stepper(a: Art, o: dict) -> None:
    """NEMA-frame stepper: chamfered square face, pilot boss, flatted shaft."""
    body = mat(o.get("body", "anod_black"))
    s = o.get("s", 330.0)
    h = o.get("h", 330.0)
    x, y = CX - s / 2 - 34, 500 - h / 2 - 10
    ground(a, CX, y + h + 46, s * 0.80, s * 0.17)
    dx, dy = 72.0, -44.0
    c = s * 0.15
    # depth: side + top, kept light enough to read as a chamfered body, not a void
    gs = a.lin([(0, body[3], None), (1, body[1], None)], 0, 0, 1, 0.4, tag="st-s")
    a.add(f'<path d="M {x+s:.1f} {y+c:.1f} L {x+s+dx:.1f} {y+c+dy:.1f} L {x+s+dx:.1f} {y+h-c+dy:.1f} L {x+s:.1f} {y+h-c:.1f} Z" fill="url(#{gs})"/>')
    gt = a.lin([(0, body[4], None), (1, body[2], None)], 0, 0, 0.5, 1, tag="st-t")
    a.add(f'<path d="M {x+c:.1f} {y:.1f} L {x+c+dx:.1f} {y+dy:.1f} L {x+s-c+dx:.1f} {y+dy:.1f} L {x+s-c:.1f} {y:.1f} Z" fill="url(#{gt})"/>')
    a.add(f'<path d="M {x+s-c:.1f} {y:.1f} L {x+s-c+dx:.1f} {y+dy:.1f} L {x+s+dx:.1f} {y+c+dy:.1f} L {x+s:.1f} {y+c:.1f} Z" fill="{body[2]}" opacity=".8"/>')
    # laminated stack lines, on the side face only
    for i in range(15):
        t = 0.08 + i * 0.84 / 14
        ya = y + c + t * (h - 2 * c)
        a.add(f'<path d="M {x+s:.1f} {ya:.1f} L {x+s+dx:.1f} {ya+dy:.1f}" stroke="#000" stroke-opacity=".26" stroke-width="2.2"/>')
    # chamfered front face
    face = (f"M {x+c:.1f} {y:.1f} L {x+s-c:.1f} {y:.1f} L {x+s:.1f} {y+c:.1f} L {x+s:.1f} {y+h-c:.1f} "
            f"L {x+s-c:.1f} {y+h:.1f} L {x+c:.1f} {y+h:.1f} L {x:.1f} {y+h-c:.1f} L {x:.1f} {y+c:.1f} Z")
    gf = a.lin([(0, body[3], None), (0.38, body[2], None), (1, body[0], None)], 0, 0, 0.45, 1, tag="st-f")
    a.add(f'<path d="{face}" fill="url(#{gf})"/>')
    edge_light(a, f"M {x+c:.1f} {y:.1f} L {x+s-c:.1f} {y:.1f}", body, 2.4, 0.5)
    edge_light(a, f"M {x:.1f} {y+c:.1f} L {x:.1f} {y+h-c:.1f}", body, 2.0, 0.32)
    # end-bell ring, pilot boss, flatted shaft
    a.add(f'<circle cx="{x+s/2:.1f}" cy="{y+h/2:.1f}" r="{s*0.30:.1f}" fill="{body[1]}" opacity=".7"/>')
    br = s * 0.20
    al = mat("alu")
    bg = a.rad([(0, al[4], None), (0.5, al[3], None), (1, al[1], None)], cx=0.36, cy=0.32, r=0.8, tag="boss")
    a.add(f'<circle cx="{x+s/2:.1f}" cy="{y+h/2:.1f}" r="{br:.1f}" fill="url(#{bg})"/>')
    a.add(f'<circle cx="{x+s/2:.1f}" cy="{y+h/2:.1f}" r="{br:.1f}" fill="none" stroke="{body[0]}" stroke-opacity=".45" stroke-width="2"/>')
    st = mat("steel")
    sr = s * 0.082
    sg = a.rad([(0, "#ffffff", None), (0.4, st[4], None), (1, st[1], None)], cx=0.34, cy=0.30, r=0.8, tag="shf")
    a.add(f'<circle cx="{x+s/2:.1f}" cy="{y+h/2:.1f}" r="{sr:.1f}" fill="url(#{sg})"/>')
    a.add(f'<path d="M {x+s/2-sr:.1f} {y+h/2-sr*0.36:.1f} A {sr:.1f} {sr:.1f} 0 0 1 {x+s/2+sr:.1f} {y+h/2-sr*0.36:.1f} Z" fill="{st[1]}" opacity=".5"/>')
    for hx, hy in ((x+c*0.62, y+c*0.62), (x+s-c*0.62, y+c*0.62), (x+c*0.62, y+h-c*0.62), (x+s-c*0.62, y+h-c*0.62)):
        a.add(f'<circle cx="{hx:.1f}" cy="{hy:.1f}" r="{s*0.042:.1f}" fill="#07090c" opacity=".9"/>')
        a.add(f'<circle cx="{hx:.1f}" cy="{hy-1.5:.1f}" r="{s*0.042:.1f}" fill="none" stroke="{body[4]}" stroke-opacity=".38" stroke-width="1.6"/>')
    if o.get("driver"):
        f_pcb_overlay(a, x + s * 0.04, y + h + 16, s * 0.92, 92, mat("pcb_black"))
    else:
        cable(a, [(x + s * 0.80, y + h - 14), (x + s + 110, y + h + 26), (x + s + 140, y + h + 100)], 12)
    spec_sheen(a, x + s * 0.05, y + c, s * 0.22, h - 2 * c, rx=10, op=0.24)

def f_pcb_overlay(a: Art, x: float, y: float, w: float, h: float, m: list[str]) -> None:
    box3d(a, x, y, w, h, 26, m, rx=6)
    for i in range(6):
        a.add(f'<rect x="{x + w*0.08 + i*w*0.145:.1f}" y="{y + h*0.30:.1f}" width="{w*0.085:.1f}" height="{h*0.36:.1f}" rx="3" fill="#0a0d11" opacity=".8"/>')


def f_lift_column(a: Art, o: dict) -> None:
    """Telescoping linear lift column, three stages."""
    m = mat(o.get("body", "alu_dark"))
    ground(a, CX, 900, 210, 34)
    # foot
    box3d(a, CX - 190, 838, 380, 44, 70, mat("anod_black"), rx=8)
    stages = [(150, 300, 838), (118, 300, 546), (92, 300, 256)]
    for i, (w, hh, by) in enumerate(stages):
        sm = [mat("alu_dark"), mat("alu"), mat("plastic_wh")][i]
        box3d(a, CX - w / 2, by - hh, w, hh, 58 - i * 8, sm, rx=6)
        spec_sheen(a, CX - w / 2 + 8, by - hh + 8, w * 0.26, hh - 16, rx=4, op=0.28)
    # top plate
    box3d(a, CX - 210, 214, 420, 40, 80, mat("alu"), rx=6)
    for sx in (CX - 160, CX - 54, CX + 54, CX + 160):
        screw_head(a, sx, 234, 12, mat("steel"))
    cable(a, [(CX + 96, 800), (CX + 210, 856), (CX + 260, 906)], 14)


def f_swerve(a: Art, o: dict) -> None:
    """Swerve module: azimuth ring, two stacked motors, belt cover, wheel."""
    plate = mat("alu")
    ground(a, CX, 902, 250, 40)
    # top mounting plate
    box3d(a, CX - 236, 252, 472, 34, 96, plate, rx=8)
    bolt_circle(a, CX, 258, 176, 40, 8, br=11, m=mat("alu_dark"))
    # drive + azimuth motors
    f_stack_motor(a, CX - 118, 92, 168, 172, mat("anod_black"), mat("anod_red"))
    f_stack_motor(a, CX + 118, 128, 138, 140, mat("anod_grey"), mat("anod_blue"))
    # azimuth bearing ring
    ring(a, CX, 292, 150, 40, 26, mat("alu_dark"))
    a.add(f'<ellipse cx="{CX:.1f}" cy="292" rx="150" ry="40" fill="none" stroke="{plate[4]}" stroke-opacity=".5" stroke-width="2"/>')
    # fork / side plates
    for sx in (CX - 156, CX + 116):
        box3d(a, sx, 316, 40, 400, 40, mat("alu_dark"), rx=8)
    # belt cover
    box3d(a, CX - 118, 352, 236, 300, 34, mat("anod_black"), rx=26)
    a.add(f'<ellipse cx="{CX:.1f}" cy="700" rx="118" ry="118" fill="{mat("anod_black")[1]}"/>')
    # wheel
    tyre = mat("rubber")
    a.add(f'<circle cx="{CX:.1f}" cy="712" r="176" fill="{tyre[1]}"/>')
    tg = a.rad([(0, tyre[3], None), (0.62, tyre[2], None), (1, tyre[0], None)], cx=0.36, cy=0.32, r=0.78, tag="tyre")
    a.add(f'<circle cx="{CX:.1f}" cy="712" r="176" fill="url(#{tg})"/>')
    for i in range(28):
        th = 2 * math.pi * i / 28
        x1, y1 = CX + 152 * math.cos(th), 712 + 152 * math.sin(th)
        x2, y2 = CX + 176 * math.cos(th), 712 + 176 * math.sin(th)
        a.add(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="#000" stroke-opacity=".28" stroke-width="7"/>')
    hg = a.rad([(0, plate[4], None), (0.5, plate[3], None), (1, plate[1], None)], cx=0.36, cy=0.32, r=0.8, tag="hub")
    a.add(f'<circle cx="{CX:.1f}" cy="712" r="92" fill="url(#{hg})"/>')
    bolt_circle(a, CX, 712, 58, 58, 6, br=12, m=mat("alu_dark"))
    a.add(f'<circle cx="{CX:.1f}" cy="712" r="26" fill="{mat("anod_red")[2]}"/>')
    spec_sheen(a, CX - 172, 560, 90, 300, rx=40, op=0.16)


def f_stack_motor(a: Art, cx: float, top: float, d: float, h: float, body, accent) -> None:
    r = d / 2
    grad = body_ramp(a, body)
    a.add(f'<path d="M {cx-r:.1f} {top:.1f} L {cx-r:.1f} {top+h:.1f} A {r:.1f} {r*0.26:.1f} 0 0 0 {cx+r:.1f} {top+h:.1f} L {cx+r:.1f} {top:.1f} Z" fill="url(#{grad})"/>')
    disc(a, cx, top, r, r * 0.26, body)
    ring(a, cx, top + h * 0.66, r, r * 0.26, h * 0.12, accent)


def f_wheel(a: Art, o: dict) -> None:
    """Traction / omni / mecanum wheel, face-on with a dish hub."""
    kind = o.get("kind", "traction")
    R = o.get("R", 300.0)
    cy = 500.0
    ground(a, CX, cy + R + 46, R * 0.86, R * 0.16)
    tyre = mat("rubber")
    tg = a.rad([(0, tyre[3], None), (0.58, tyre[2], None), (1, tyre[0], None)], cx=0.36, cy=0.30, r=0.80, tag="tyre")
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R:.1f}" fill="url(#{tg})"/>')
    if kind == "omni":
        for i in range(12):
            th = 2 * math.pi * i / 12
            rx_, ry_ = CX + (R * 0.86) * math.cos(th), cy + (R * 0.86) * math.sin(th)
            ang = math.degrees(th) + 90
            a.add(f'<rect x="{rx_-R*0.115:.1f}" y="{ry_-R*0.052:.1f}" width="{R*0.23:.1f}" height="{R*0.105:.1f}" rx="{R*0.052:.1f}" '
                  f'fill="{mat("plastic_bk")[3]}" transform="rotate({ang:.1f} {rx_:.1f} {ry_:.1f})"/>')
    elif kind == "mecanum":
        for i in range(10):
            th = 2 * math.pi * i / 10
            rx_, ry_ = CX + (R * 0.80) * math.cos(th), cy + (R * 0.80) * math.sin(th)
            ang = math.degrees(th) + 45
            a.add(f'<rect x="{rx_-R*0.16:.1f}" y="{ry_-R*0.062:.1f}" width="{R*0.32:.1f}" height="{R*0.124:.1f}" rx="{R*0.062:.1f}" '
                  f'fill="{mat("plastic_bk")[3]}" transform="rotate({ang:.1f} {rx_:.1f} {ry_:.1f})"/>')
    else:
        for i in range(36):
            th = 2 * math.pi * i / 36
            a.add(f'<line x1="{CX + R*0.86*math.cos(th):.1f}" y1="{cy + R*0.86*math.sin(th):.1f}" '
                  f'x2="{CX + R*math.cos(th):.1f}" y2="{cy + R*math.sin(th):.1f}" stroke="#000" stroke-opacity=".26" stroke-width="8"/>')
    hub = mat(o.get("hub", "alu_dark"))
    hg = a.rad([(0, hub[4], None), (0.42, hub[3], None), (1, hub[1], None)], cx=0.36, cy=0.30, r=0.82, tag="hub")
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.56:.1f}" fill="url(#{hg})"/>')
    for i in range(6):
        th = 2 * math.pi * i / 6 + 0.3
        a.add(f'<ellipse cx="{CX + R*0.34*math.cos(th):.1f}" cy="{cy + R*0.34*math.sin(th):.1f}" rx="{R*0.11:.1f}" ry="{R*0.11:.1f}" fill="#0a0d11" opacity=".55"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.17:.1f}" fill="{mat("alu")[3]}"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.08:.1f}" fill="#0a0d11" opacity=".85"/>')
    spec_sheen(a, CX - R, cy - R * 0.9, R * 0.7, R * 1.7, rx=R * 0.3, op=0.14, angle=-18)


def f_extrusion(a: Art, o: dict) -> None:
    """T-slot aluminium extrusion in perspective — the profile is the graphic."""
    m = mat("alu")
    n = o.get("slots", 4)
    L = o.get("L", 520.0)
    s = 250.0 if n == 4 else 190.0
    x, y = CX - s / 2 - 60, 500 - s / 2 - 40
    ground(a, CX, y + s + L * 0.34 + 34, s * 0.92, s * 0.20)
    dx, dy = L * 0.52, -L * 0.34
    # extruded side + top faces
    gs = a.lin([(0, m[1], None), (1, m[0], None)], 0, 0, 1, 0.3, tag="ex-s")
    gt = a.lin([(0, m[4], None), (1, m[2], None)], 0, 0, 0.4, 1, tag="ex-t")
    a.add(f'<path d="M {x+s:.1f} {y:.1f} L {x+s+dx:.1f} {y+dy:.1f} L {x+s+dx:.1f} {y+dy+s:.1f} L {x+s:.1f} {y+s:.1f} Z" fill="url(#{gs})"/>')
    a.add(f'<path d="M {x:.1f} {y:.1f} L {x+dx:.1f} {y+dy:.1f} L {x+s+dx:.1f} {y+dy:.1f} L {x+s:.1f} {y:.1f} Z" fill="url(#{gt})"/>')
    # front profile
    gf = a.lin([(0, m[4], None), (0.42, m[3], None), (1, m[1], None)], 0, 0, 0.4, 1, tag="ex-f")
    a.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{s:.1f}" height="{s:.1f}" rx="{s*0.05:.1f}" fill="url(#{gf})"/>')
    cells = 2 if n == 4 else 1
    cw = s / cells
    for r_ in range(cells):
        for c_ in range(cells):
            ox, oy = x + c_ * cw, y + r_ * cw
            # T-slot opening on each of the four edges of the cell
            t = cw * 0.20
            a.add(f'<rect x="{ox+cw/2-t/2:.1f}" y="{oy+cw*0.06:.1f}" width="{t:.1f}" height="{cw*0.30:.1f}" fill="{m[0]}" opacity=".85"/>')
            a.add(f'<rect x="{ox+cw/2-t/2:.1f}" y="{oy+cw*0.64:.1f}" width="{t:.1f}" height="{cw*0.30:.1f}" fill="{m[0]}" opacity=".85"/>')
            a.add(f'<rect x="{ox+cw*0.06:.1f}" y="{oy+cw/2-t/2:.1f}" width="{cw*0.30:.1f}" height="{t:.1f}" fill="{m[0]}" opacity=".85"/>')
            a.add(f'<rect x="{ox+cw*0.64:.1f}" y="{oy+cw/2-t/2:.1f}" width="{cw*0.30:.1f}" height="{t:.1f}" fill="{m[0]}" opacity=".85"/>')
            a.add(f'<circle cx="{ox+cw/2:.1f}" cy="{oy+cw/2:.1f}" r="{cw*0.16:.1f}" fill="{m[0]}" opacity=".7"/>')
            a.add(f'<circle cx="{ox+cw/2:.1f}" cy="{oy+cw/2:.1f}" r="{cw*0.11:.1f}" fill="#0c0f13" opacity=".55"/>')
    edge_light(a, f"M {x+s*0.05:.1f} {y:.1f} L {x+s-s*0.05:.1f} {y:.1f}", m, 2.4, 0.7)
    spec_sheen(a, x + 10, y + 10, s * 0.24, s - 20, rx=8, op=0.30)



def f_fastener_set(a: Art, o: dict) -> None:
    """Sorted hardware case: shallow lid, six generous bins of real fasteners."""
    case = mat(o.get("body", "plastic_bk"))
    x, y, w, h = CX - 350, 330, 700, 400
    ground(a, CX, y + h + 44, 360, 46)
    box3d(a, x, y, w, h, 56, case, rx=22)
    a.add(f'<rect x="{x+16:.1f}" y="{y+16:.1f}" width="{w-32:.1f}" height="{h-32:.1f}" rx="14" fill="#0a0c0f" opacity=".42"/>')
    cols, rows = 3, 2
    cw, ch = (w - 56) / cols, (h - 56) / rows
    kinds = ["cap", "nut", "insert", "washer", "cap", "nut"]
    mats_ = [mat("steel"), mat("alu_dark"), mat("brass"), mat("steel"), mat("anod_black"), mat("brass")]
    for r_ in range(rows):
        for c_ in range(cols):
            i = r_ * cols + c_
            bx, by = x + 28 + c_ * cw, y + 28 + r_ * ch
            bw, bh = cw - 14, ch - 14
            a.add(f'<rect x="{bx:.1f}" y="{by:.1f}" width="{bw:.1f}" height="{bh:.1f}" rx="10" fill="{case[1]}"/>')
            a.add(f'<rect x="{bx+5:.1f}" y="{by+5:.1f}" width="{bw-10:.1f}" height="{bh-10:.1f}" rx="8" fill="#070a0d" opacity=".55"/>')
            mm, k = mats_[i], kinds[i]
            for j in range(6):
                px = bx + bw * (0.22 + (j % 3) * 0.28)
                py = by + bh * (0.34 + (j // 3) * 0.34)
                if k == "cap":
                    a.add(f'<rect x="{px-9:.1f}" y="{py-6:.1f}" width="18" height="{bh*0.30:.1f}" rx="4" fill="{mm[2]}"/>')
                    a.add(f'<rect x="{px-9:.1f}" y="{py-6:.1f}" width="6" height="{bh*0.30:.1f}" fill="{mm[4]}" opacity=".6"/>')
                    screw_head(a, px, py - 8, 15, mm)
                elif k == "nut":
                    pts = " ".join(f"{px+17*math.cos(math.pi/6+q*math.pi/3):.1f},{py+17*math.sin(math.pi/6+q*math.pi/3)*0.86:.1f}" for q in range(6))
                    a.add(f'<polygon points="{pts}" fill="{mm[3]}"/>')
                    a.add(f'<polygon points="{pts}" fill="none" stroke="{mm[0]}" stroke-opacity=".6" stroke-width="2"/>')
                    a.add(f'<ellipse cx="{px:.1f}" cy="{py:.1f}" rx="8" ry="7" fill="#0a0d11" opacity=".85"/>')
                elif k == "insert":
                    a.add(f'<rect x="{px-10:.1f}" y="{py-15:.1f}" width="20" height="30" rx="4" fill="{mm[3]}"/>')
                    for q in range(4):
                        a.add(f'<rect x="{px-10:.1f}" y="{py-12+q*7:.1f}" width="20" height="2.6" fill="{mm[0]}" opacity=".55"/>')
                    a.add(f'<ellipse cx="{px:.1f}" cy="{py-15:.1f}" rx="10" ry="4" fill="#0a0d11" opacity=".7"/>')
                else:
                    a.add(f'<ellipse cx="{px:.1f}" cy="{py:.1f}" rx="17" ry="15" fill="{mm[3]}"/>')
                    a.add(f'<ellipse cx="{px:.1f}" cy="{py:.1f}" rx="7.5" ry="6.5" fill="#0a0d11" opacity=".8"/>')
    spec_sheen(a, x + 18, y + 14, w * 0.24, h - 28, rx=16, op=0.10)

def f_bearing(a: Art, o: dict) -> None:
    """Deep-groove / thin-section bearing, face-on with visible balls."""
    R = o.get("R", 290.0)
    cy = 500.0
    st = mat("steel")
    ground(a, CX, cy + R + 42, R * 0.8, R * 0.15)
    og = a.rad([(0, st[4], None), (0.4, st[3], None), (1, st[1], None)], cx=0.36, cy=0.30, r=0.82, tag="or")
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R:.1f}" fill="url(#{og})"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.855:.1f}" fill="{st[0]}" opacity=".55"/>')
    n = o.get("balls", 14)
    br = R * 0.093
    for i in range(n):
        th = 2 * math.pi * i / n
        bx, by = CX + R * 0.74 * math.cos(th), cy + R * 0.74 * math.sin(th)
        bg = a.rad([(0, "#ffffff", None), (0.34, st[4], None), (0.78, st[2], None), (1, st[0], None)], cx=0.34, cy=0.30, r=0.8, tag="ball")
        a.add(f'<circle cx="{bx:.1f}" cy="{by:.1f}" r="{br:.1f}" fill="url(#{bg})"/>')
    ig = a.rad([(0, st[4], None), (0.42, st[3], None), (1, st[1], None)], cx=0.36, cy=0.30, r=0.82, tag="ir")
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.60:.1f}" fill="url(#{ig})"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.42:.1f}" fill="#0d1116"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="{cy:.1f}" r="{R*0.42:.1f}" fill="none" stroke="{st[4]}" stroke-opacity=".45" stroke-width="3"/>')
    spec_sheen(a, CX - R, cy - R, R * 0.66, R * 2, rx=R * 0.3, op=0.20, angle=-20)




def f_plate(a: Art, o: dict) -> None:
    """Laser-cut sheet-metal part: real thickness, a bent flange, hole pattern."""
    m = mat(o.get("body", "alu"))
    d = mat("alu_dark")
    w, h = o.get("w", 560.0), o.get("h", 260.0)
    th = 20.0
    fh = 168.0
    x, y = CX - w / 2, 430.0
    ground(a, CX, y + th + fh + 46, w * 0.54, 38)
    dx, dy = 150.0, -108.0
    gt = a.lin([(0, m[4], None), (0.40, m[3], None), (1, m[2], None)], 0, 0, 0.45, 1, tag="pl-t")
    a.add(f'<path d="M {x:.1f} {y:.1f} L {x+dx:.1f} {y+dy:.1f} L {x+w+dx:.1f} {y+dy:.1f} L {x+w:.1f} {y:.1f} Z" fill="url(#{gt})"/>')
    # hole pattern + lightening cut-out, projected onto the top face
    for r_ in range(3):
        for c_ in range(7):
            u, v = (c_ + 0.5) / 7, (r_ + 0.5) / 3
            hx, hy = x + u * w + v * dx, y + v * dy
            rr = 16 if (r_ + c_) % 3 else 22
            a.add(f'<ellipse cx="{hx:.1f}" cy="{hy:.1f}" rx="{rr:.1f}" ry="{rr*0.62:.1f}" fill="{d[1]}" opacity=".85"/>')
            a.add(f'<ellipse cx="{hx:.1f}" cy="{hy+2:.1f}" rx="{rr*0.82:.1f}" ry="{rr*0.48:.1f}" fill="#0a0d11" opacity=".62"/>')
    a.add(f'<ellipse cx="{x+w*0.50+dx*0.5:.1f}" cy="{y+dy*0.5:.1f}" rx="80" ry="43" fill="{d[0]}" opacity=".55"/>')
    a.add(f'<ellipse cx="{x+w*0.50+dx*0.5:.1f}" cy="{y+dy*0.5+2:.1f}" rx="74" ry="38" fill="#0a0d11" opacity=".45"/>')
    # front edge — the thickness that makes it steel rather than paper
    ge = a.lin([(0, m[2], None), (1, d[1], None)], 0, 0, 0, 1, tag="pl-e")
    a.add(f'<path d="M {x:.1f} {y:.1f} L {x+w:.1f} {y:.1f} L {x+w:.1f} {y+th:.1f} L {x:.1f} {y+th:.1f} Z" fill="url(#{ge})"/>')
    a.add(f'<path d="M {x+w:.1f} {y:.1f} L {x+w+dx:.1f} {y+dy:.1f} L {x+w+dx:.1f} {y+dy+th:.1f} L {x+w:.1f} {y+th:.1f} Z" fill="{d[0]}"/>')
    # bent-up flange, shaded a full step darker so the bend reads
    if o.get("bend", True):
        gb = a.lin([(0, d[3], None), (0.42, d[2], None), (1, d[0], None)], 0, 0, 0.35, 1, tag="pl-b")
        a.add(f'<path d="M {x:.1f} {y+th:.1f} L {x+w:.1f} {y+th:.1f} L {x+w:.1f} {y+th+fh:.1f} L {x:.1f} {y+th+fh:.1f} Z" fill="url(#{gb})"/>')
        a.add(f'<path d="M {x+w:.1f} {y+th:.1f} L {x+w+dx*0.13:.1f} {y+th+dy*0.13:.1f} L {x+w+dx*0.13:.1f} {y+th+dy*0.13+fh:.1f} L {x+w:.1f} {y+th+fh:.1f} Z" fill="{d[0]}" opacity=".92"/>')
        edge_light(a, f"M {x:.1f} {y+th:.1f} L {x+w:.1f} {y+th:.1f}", m, 2.6, 0.55)
        for i in range(4):
            hx = x + w * (0.15 + i * 0.235)
            a.add(f'<circle cx="{hx:.1f}" cy="{y+th+fh*0.50:.1f}" r="21" fill="#0a0d11" opacity=".62"/>')
            a.add(f'<circle cx="{hx:.1f}" cy="{y+th+fh*0.50-2:.1f}" r="21" fill="none" stroke="{d[4]}" stroke-opacity=".40" stroke-width="2"/>')
        spec_sheen(a, x + 12, y + th + 8, w * 0.26, fh - 16, rx=6, op=0.16)
    edge_light(a, f"M {x:.1f} {y:.1f} L {x+dx:.1f} {y+dy:.1f}", m, 2.2, 0.6)
    spec_sheen(a, x + 24, y + dy + 8, w * 0.28, abs(dy) + 10, rx=6, op=0.22)

def f_pcb(a: Art, o: dict) -> None:
    """A board: CAN adapter, servo driver, distribution board, carrier."""
    m = mat(o.get("body", "pcb_black"))
    w, h = o.get("w", 560.0), o.get("h", 340.0)
    x, y = CX - w / 2, 500 - h / 2
    ground(a, CX, y + h + 40, w * 0.50, 30)
    box3d(a, x, y, w, h, 26, m, rx=12)
    # gold traces
    tr = mat("brass")
    for i in range(9):
        ty = y + h * 0.14 + i * h * 0.085
        a.add(f'<path d="M {x+w*0.08:.1f} {ty:.1f} H {x+w*0.44:.1f} L {x+w*0.52:.1f} {ty+14:.1f} H {x+w*0.90:.1f}" '
              f'fill="none" stroke="{tr[3]}" stroke-opacity=".28" stroke-width="2.4"/>')
    # main IC
    icw, ich = w * 0.26, h * 0.26
    a.add(f'<rect x="{CX-icw/2:.1f}" y="{y+h*0.30:.1f}" width="{icw:.1f}" height="{ich:.1f}" rx="6" fill="{mat("plastic_bk")[2]}"/>')
    a.add(f'<rect x="{CX-icw/2:.1f}" y="{y+h*0.30:.1f}" width="{icw:.1f}" height="{ich*0.32:.1f}" rx="6" fill="{mat("plastic_bk")[4]}" opacity=".25"/>')
    for i in range(10):
        px = CX - icw / 2 + 6 + i * (icw - 12) / 9
        a.add(f'<rect x="{px:.1f}" y="{y+h*0.30+ich:.1f}" width="4" height="9" fill="{tr[3]}" opacity=".8"/>')
        a.add(f'<rect x="{px:.1f}" y="{y+h*0.30-9:.1f}" width="4" height="9" fill="{tr[3]}" opacity=".8"/>')
    # connectors
    for i, cxp in enumerate((x + w * 0.10, x + w * 0.10, x + w * 0.72)):
        cy_ = y + h * (0.66 if i < 2 else 0.30)
        off = i * 0 if i != 1 else 0
        a.add(f'<rect x="{cxp:.1f}" y="{cy_ + (0 if i!=1 else h*0.16):.1f}" width="{w*0.17:.1f}" height="{h*0.14:.1f}" rx="4" fill="#0b0e12"/>')
        a.add(f'<rect x="{cxp+4:.1f}" y="{cy_+3 + (0 if i!=1 else h*0.16):.1f}" width="{w*0.15:.1f}" height="{h*0.05:.1f}" rx="2" fill="{m[4]}" opacity=".3"/>')
    # USB-A / type-C shell
    if o.get("usb", True):
        a.add(f'<rect x="{x+w-26:.1f}" y="{y+h*0.36:.1f}" width="70" height="{h*0.20:.1f}" rx="7" fill="{mat("steel")[3]}"/>')
        a.add(f'<rect x="{x+w-20:.1f}" y="{y+h*0.40:.1f}" width="58" height="{h*0.11:.1f}" rx="5" fill="#0a0d11"/>')
    # status LEDs
    for i, c in enumerate(("#37d67a", "#ffb020", "#ff4d4f")):
        a.add(f'<circle cx="{x+w*0.30+i*26:.1f}" cy="{y+h*0.80:.1f}" r="7" fill="{c}"/>')
        gl = a.rad([(0, c, 0.55), (1, c, 0.0)], tag="led")
        a.add(f'<circle cx="{x+w*0.30+i*26:.1f}" cy="{y+h*0.80:.1f}" r="20" fill="url(#{gl})"/>')
    # mounting holes
    for hx, hy in ((x + 18, y + 18), (x + w - 18, y + 18), (x + 18, y + h - 18), (x + w - 18, y + h - 18)):
        a.add(f'<circle cx="{hx:.1f}" cy="{hy:.1f}" r="9" fill="{tr[3]}" opacity=".7"/>')
        a.add(f'<circle cx="{hx:.1f}" cy="{hy:.1f}" r="5" fill="#0a0d11"/>')
    spec_sheen(a, x + 12, y + 10, w * 0.24, h - 20, rx=8, op=0.13)


def _lens(a: Art, cx: float, cy: float, r: float, tint="glass") -> None:
    g = mat(tint)
    a.add(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="{mat("plastic_bk")[1]}"/>')
    lg = a.rad([(0, g[3], None), (0.45, g[2], None), (0.86, g[0], None), (1, "#000", None)], cx=0.36, cy=0.32, r=0.78, tag="lens")
    a.add(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r*0.82:.1f}" fill="url(#{lg})"/>')
    a.add(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r*0.44:.1f}" fill="#05080b"/>')
    a.add(f'<ellipse cx="{cx-r*0.30:.1f}" cy="{cy-r*0.34:.1f}" rx="{r*0.30:.1f}" ry="{r*0.19:.1f}" fill="#ffffff" opacity=".62" transform="rotate(-32 {cx-r*0.30:.1f} {cy-r*0.34:.1f})"/>')
    a.add(f'<circle cx="{cx+r*0.34:.1f}" cy="{cy+r*0.36:.1f}" r="{r*0.10:.1f}" fill="#8fd3ff" opacity=".35"/>')


def f_depth_camera(a: Art, o: dict) -> None:
    """RealSense-style stereo depth bar: anodised body, three apertures."""
    m = mat(o.get("body", "alu_dark"))
    w, h = o.get("w", 700.0), o.get("h", 180.0)
    x, y = CX - w / 2, 500 - h / 2
    ground(a, CX, y + h + 40, w * 0.46, 30)
    box3d(a, x, y, w, h, 54, m, rx=h * 0.28)
    face = a.lin([(0, mat("plastic_bk")[2], None), (0.5, mat("plastic_bk")[1], None), (1, mat("plastic_bk")[0], None)], 0, 0, 0.3, 1, tag="cf")
    a.add(f'<rect x="{x+10:.1f}" y="{y+12:.1f}" width="{w-20:.1f}" height="{h-24:.1f}" rx="{h*0.22:.1f}" fill="url(#{face})"/>')
    ly = y + h / 2
    _lens(a, x + w * 0.20, ly, h * 0.30)
    _lens(a, x + w * 0.80, ly, h * 0.30)
    _lens(a, CX, ly, h * 0.22, tint="anod_blue")
    a.add(f'<circle cx="{x + w*0.36:.1f}" cy="{ly:.1f}" r="{h*0.075:.1f}" fill="{mat("anod_red")[2]}" opacity=".9"/>')
    for tx in (x + 26, x + w - 26):
        a.add(f'<circle cx="{tx:.1f}" cy="{ly:.1f}" r="9" fill="{m[0]}"/>')
        a.add(f'<circle cx="{tx:.1f}" cy="{ly:.1f}" r="5" fill="#0a0d11"/>')
    spec_sheen(a, x + 14, y + 8, w * 0.30, h - 16, rx=h * 0.2, op=0.16)


def f_cam_module(a: Art, o: dict) -> None:
    """Board-level camera module: PCB, lens barrel, ribbon or USB tail."""
    m = mat(o.get("body", "pcb_black"))
    w, h = o.get("w", 400.0), o.get("h", 400.0)
    x, y = CX - w / 2, 500 - h / 2 - 20
    ground(a, CX, y + h + 46, w * 0.56, 34)
    box3d(a, x, y, w, h, 24, m, rx=14)
    bw = w * 0.52
    a.add(f'<rect x="{CX-bw/2:.1f}" y="{y+h*0.10:.1f}" width="{bw:.1f}" height="{bw:.1f}" rx="{bw*0.16:.1f}" fill="{mat("plastic_bk")[2]}"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="{y+h*0.10+bw/2:.1f}" r="{bw*0.42:.1f}" fill="{mat("plastic_bk")[1]}"/>')
    for i in range(22):
        th = 2 * math.pi * i / 22
        a.add(f'<line x1="{CX + bw*0.36*math.cos(th):.1f}" y1="{y+h*0.10+bw/2 + bw*0.36*math.sin(th):.1f}" '
              f'x2="{CX + bw*0.42*math.cos(th):.1f}" y2="{y+h*0.10+bw/2 + bw*0.42*math.sin(th):.1f}" stroke="#000" stroke-opacity=".4" stroke-width="4"/>')
    _lens(a, CX, y + h * 0.10 + bw / 2, bw * 0.31)
    for i, c in enumerate(("#37d67a", "#4da3ff")):
        a.add(f'<circle cx="{x+w*0.20+i*30:.1f}" cy="{y+h*0.82:.1f}" r="7" fill="{c}"/>')
    a.add(f'<rect x="{x+w*0.56:.1f}" y="{y+h*0.76:.1f}" width="{w*0.26:.1f}" height="{h*0.11:.1f}" rx="4" fill="#0b0e12"/>')
    if o.get("tail", True):
        cable(a, [(x + w * 0.82, y + h * 0.81), (x + w + 96, y + h * 0.94), (x + w + 130, y + h + 60)], 12)
    spec_sheen(a, x + 12, y + 10, w * 0.26, h - 20, rx=10, op=0.14)


def f_ego_camera(a: Art, o: dict) -> None:
    """Head-mounted egocentric camera: action-cam block on a mount arm."""
    m = mat(o.get("body", "anod_black"))
    w, h = 400.0, 330.0
    x, y = CX - w / 2, 380.0
    ground(a, CX, 812, 250, 38)
    # mount arm + shoe
    box3d(a, CX - 130, 700, 260, 40, 60, mat("alu_dark"), rx=10)
    box3d(a, CX - 34, 640, 68, 70, 42, mat("alu_dark"), rx=8)
    box3d(a, x, y, w, h, 74, m, rx=44)
    a.add(f'<rect x="{x+16:.1f}" y="{y+18:.1f}" width="{w-32:.1f}" height="{h-36:.1f}" rx="34" fill="{mat("plastic_bk")[1]}"/>')
    _lens(a, x + w * 0.36, y + h * 0.46, 82)
    a.add(f'<circle cx="{x+w*0.74:.1f}" cy="{y+h*0.30:.1f}" r="16" fill="{mat("plastic_bk")[3]}"/>')
    a.add(f'<circle cx="{x+w*0.74:.1f}" cy="{y+h*0.30:.1f}" r="8" fill="{mat("anod_red")[2]}"/>')
    for i in range(4):
        a.add(f'<circle cx="{x+w*0.76:.1f}" cy="{y+h*0.62+i*17:.1f}" r="4.5" fill="#0a0d11" opacity=".8"/>')
    a.add(f'<rect x="{x+w*0.30:.1f}" y="{y-16:.1f}" width="{w*0.40:.1f}" height="20" rx="8" fill="{m[1]}"/>')
    spec_sheen(a, x + 18, y + 14, w * 0.28, h - 28, rx=30, op=0.20)


def f_lidar(a: Art, o: dict) -> None:
    """2-D scanning lidar (drum) or 3-D dome lidar."""
    dome = o.get("dome", False)
    m = mat(o.get("body", "anod_black"))
    d = o.get("d", 400.0)
    ground(a, CX, 762, d * 0.60, d * 0.14)
    base_h = 92.0
    cylinder(a, CX, 660, d, base_h, m)
    ring(a, CX, 660 + base_h * 0.62, d / 2, d / 2 * 0.26, 16, mat("alu_dark"))
    if dome:
        dg = a.rad([(0, mat("glass")[3], None), (0.55, mat("glass")[2], None), (1, mat("glass")[0], None)], cx=0.36, cy=0.28, r=0.8, tag="dome")
        a.add(f'<path d="M {CX-d/2:.1f} 660 A {d/2:.1f} {d*0.46:.1f} 0 0 1 {CX+d/2:.1f} 660 Z" fill="url(#{dg})"/>')
        a.add(f'<ellipse cx="{CX-d*0.14:.1f}" cy="{560:.1f}" rx="{d*0.16:.1f}" ry="{d*0.09:.1f}" fill="#fff" opacity=".30" transform="rotate(-28 {CX-d*0.14:.1f} 560)"/>')
    else:
        top_h = 150.0
        cylinder(a, CX, 660 - top_h, d * 0.90, top_h, mat("plastic_wh"))
        # scan window band
        wm = mat("glass")
        wg = a.lin([(0, wm[1], None), (0.4, wm[3], None), (1, wm[0], None)], 0, 0, 1, 0, tag="win")
        a.add(f'<rect x="{CX-d*0.45:.1f}" y="{660-top_h*0.76:.1f}" width="{d*0.90:.1f}" height="{top_h*0.44:.1f}" fill="url(#{wg})"/>')
        a.add(f'<rect x="{CX-d*0.45:.1f}" y="{660-top_h*0.76:.1f}" width="{d*0.28:.1f}" height="{top_h*0.44:.1f}" fill="#fff" opacity=".16"/>')
        disc(a, CX, 660 - top_h, d * 0.45, d * 0.45 * 0.26, mat("plastic_wh"))
    for i in range(3):
        a.add(f'<ellipse cx="{CX:.1f}" cy="{700+i*10:.1f}" rx="{d*0.52+i*26:.1f}" ry="{(d*0.52+i*26)*0.26:.1f}" fill="none" stroke="{mat("anod_blue")[3]}" stroke-opacity="{0.20-i*0.05:.2f}" stroke-width="2"/>')
    cable(a, [(CX + d * 0.46, 720), (CX + d * 0.72, 780), (CX + d * 0.66, 866)], 11)


def f_imu(a: Art, o: dict) -> None:
    """Small IMU / sensor breakout — one chip, castellated edges."""
    m = mat(o.get("body", "pcb_blue"))
    w, h = 440.0, 300.0
    x, y = CX - w / 2, 500 - h / 2
    ground(a, CX, y + h + 36, w * 0.48, 26)
    box3d(a, x, y, w, h, 20, m, rx=12)
    a.add(f'<rect x="{CX-70:.1f}" y="{y+h*0.28:.1f}" width="140" height="{h*0.34:.1f}" rx="8" fill="{mat("plastic_bk")[2]}"/>')
    a.add(f'<rect x="{CX-70:.1f}" y="{y+h*0.28:.1f}" width="140" height="{h*0.11:.1f}" rx="8" fill="{mat("plastic_bk")[4]}" opacity=".22"/>')
    a.add(f'<circle cx="{CX-52:.1f}" cy="{y+h*0.36:.1f}" r="6" fill="{mat("plastic_bk")[4]}" opacity=".5"/>')
    for i in range(8):
        px = x + w * 0.10 + i * w * 0.10
        a.add(f'<rect x="{px:.1f}" y="{y+h-16:.1f}" width="18" height="16" rx="3" fill="{mat("brass")[3]}" opacity=".85"/>')
        a.add(f'<rect x="{px:.1f}" y="{y:.1f}" width="18" height="16" rx="3" fill="{mat("brass")[3]}" opacity=".85"/>')
    for i in range(4):
        a.add(f'<rect x="{x+w*0.72+ (i%2)*30:.1f}" y="{y+h*0.30+(i//2)*34:.1f}" width="22" height="12" rx="3" fill="{mat("plastic_bk")[3]}"/>')
    a.add(f'<circle cx="{x+w*0.16:.1f}" cy="{y+h*0.72:.1f}" r="7" fill="#37d67a"/>')
    spec_sheen(a, x + 12, y + 10, w * 0.24, h - 20, rx=8, op=0.14)


def f_compute(a: Art, o: dict) -> None:
    """Jetson-class dev kit / mini PC: finned heatsink, module, I/O wall."""
    shell = mat(o.get("body", "anod_black"))
    w, h = 620.0, 300.0
    x, y = CX - w / 2, 430.0
    ground(a, CX, y + h + 46, w * 0.52, 36)
    box3d(a, x, y, w, h, 96, shell, rx=14)
    # heatsink fins on the top face
    dx, dy = 96 * 0.52, -96 * 0.58
    for i in range(16):
        fx = x + 22 + i * (w - 44) / 15
        a.add(f'<path d="M {fx:.1f} {y:.1f} L {fx+dx:.1f} {y+dy:.1f}" stroke="{shell[4]}" stroke-opacity=".22" stroke-width="4"/>')
        a.add(f'<path d="M {fx+3:.1f} {y:.1f} L {fx+3+dx:.1f} {y+dy:.1f}" stroke="#000" stroke-opacity=".35" stroke-width="3"/>')
    # fan
    a.add(f'<circle cx="{CX + dx*0.5:.1f}" cy="{y + dy*0.5:.1f}" r="0.1" fill="none"/>')
    # I/O wall
    io = y + h * 0.42
    ports = [("#0b0e12", 88, 34), ("#0b0e12", 62, 30), ("#12406e", 54, 26), ("#12406e", 54, 26), ("#0b0e12", 40, 22)]
    px = x + 40
    for c, pw, ph in ports:
        a.add(f'<rect x="{px:.1f}" y="{io:.1f}" width="{pw:.1f}" height="{ph:.1f}" rx="4" fill="{c}"/>')
        a.add(f'<rect x="{px+3:.1f}" y="{io+3:.1f}" width="{pw-6:.1f}" height="{ph*0.30:.1f}" rx="2" fill="{shell[4]}" opacity=".18"/>')
        px += pw + 22
    a.add(f'<rect x="{x+w*0.80:.1f}" y="{io+2:.1f}" width="46" height="26" rx="13" fill="{mat("alu")[2]}"/>')
    for i, c in enumerate(("#37d67a", "#4da3ff")):
        a.add(f'<circle cx="{x+42+i*26:.1f}" cy="{y+h*0.78:.1f}" r="7" fill="{c}"/>')
    a.add(f'<rect x="{x+w*0.40:.1f}" y="{y+h*0.74:.1f}" width="{w*0.34:.1f}" height="{h*0.13:.1f}" rx="5" fill="{shell[1]}"/>')
    spec_sheen(a, x + 14, y + 12, w * 0.24, h - 24, rx=10, op=0.16)


def f_switch(a: Art, o: dict) -> None:
    """Managed ethernet switch: 1U-ish metal box, RJ45 bank, SFP cages."""
    m = mat(o.get("body", "anod_black"))
    w, h = 700.0, 190.0
    x, y = CX - w / 2, 500 - h / 2
    ground(a, CX, y + h + 40, w * 0.48, 28)
    box3d(a, x, y, w, h, 70, m, rx=10)
    for i in range(4):
        px = x + 34 + i * 104
        a.add(f'<rect x="{px:.1f}" y="{y+h*0.34:.1f}" width="76" height="62" rx="5" fill="#0a0d11"/>')
        a.add(f'<rect x="{px+8:.1f}" y="{y+h*0.34:.1f}" width="60" height="20" rx="3" fill="{m[3]}" opacity=".45"/>')
        a.add(f'<circle cx="{px+14:.1f}" cy="{y+h*0.26:.1f}" r="5" fill="#37d67a"/>')
    for i in range(2):
        px = x + 470 + i * 104
        a.add(f'<rect x="{px:.1f}" y="{y+h*0.34:.1f}" width="86" height="58" rx="5" fill="#0a0d11"/>')
        a.add(f'<rect x="{px+6:.1f}" y="{y+h*0.40:.1f}" width="74" height="30" rx="3" fill="{mat("anod_blue")[1]}"/>')
    spec_sheen(a, x + 12, y + 10, w * 0.26, h - 20, rx=8, op=0.14)


def f_cable_coil(a: Art, o: dict) -> None:
    """Coiled harness with moulded connectors."""
    m = mat(o.get("body", "plastic_bk"))
    ground(a, CX, 790, 260, 40)
    for i in range(5):
        r = 250 - i * 26
        a.add(f'<ellipse cx="{CX:.1f}" cy="{500 + i*14:.1f}" rx="{r:.1f}" ry="{r*0.42:.1f}" fill="none" stroke="{m[0]}" stroke-width="26"/>')
        a.add(f'<ellipse cx="{CX:.1f}" cy="{500 + i*14:.1f}" rx="{r:.1f}" ry="{r*0.42:.1f}" fill="none" stroke="{m[2]}" stroke-width="17"/>')
        a.add(f'<ellipse cx="{CX:.1f}" cy="{500 + i*14 - 4:.1f}" rx="{r:.1f}" ry="{r*0.42:.1f}" fill="none" stroke="{m[4]}" stroke-opacity=".28" stroke-width="5"/>')
    for sx, col in ((CX - 300, o.get("c1", "anod_black")), (CX + 300, o.get("c2", "anod_red"))):
        cm = mat(col)
        box3d(a, sx - 54, 300, 108, 120, 34, cm, rx=12)
        a.add(f'<rect x="{sx-38:.1f}" y="{316:.1f}" width="76" height="46" rx="6" fill="#0a0d11" opacity=".8"/>')
        for i in range(4):
            a.add(f'<rect x="{sx-30+i*17:.1f}" y="{324:.1f}" width="9" height="30" rx="2" fill="{mat("brass")[3]}" opacity=".8"/>')



def f_tool_kit(a: Art, o: dict) -> None:
    """Precision driver: aluminium handle above its bit case."""
    case = mat(o.get("body", "alu"))
    hm = mat(o.get("handle", "alu_dark"))
    ground(a, CX, 812, 330, 44)
    # driver, laid across the top
    hy, hh = 250.0, 92.0
    hx0, hw = CX - 250, 400.0
    a.add(f'<rect x="{hx0:.1f}" y="{hy:.1f}" width="{hw:.1f}" height="{hh:.1f}" rx="{hh/2:.1f}" fill="{hm[2]}"/>')
    gh = a.lin([(0, hm[4], None), (0.30, hm[3], None), (0.62, hm[2], None), (1, hm[0], None)], 0, 0, 0, 1, tag="hnd")
    a.add(f'<rect x="{hx0:.1f}" y="{hy:.1f}" width="{hw:.1f}" height="{hh:.1f}" rx="{hh/2:.1f}" fill="url(#{gh})"/>')
    for i in range(16):
        a.add(f'<rect x="{hx0+hw*0.10+i*hw*0.030:.1f}" y="{hy+6:.1f}" width="3" height="{hh-12:.1f}" rx="1.5" fill="#000" opacity=".16"/>')
    a.add(f'<circle cx="{hx0+hw-26:.1f}" cy="{hy+hh/2:.1f}" r="{hh*0.30:.1f}" fill="{mat("anod_black")[2]}"/>')
    # collet + installed bit
    a.add(f'<rect x="{hx0-70:.1f}" y="{hy+hh*0.28:.1f}" width="76" height="{hh*0.44:.1f}" rx="8" fill="{mat("steel")[3]}"/>')
    a.add(f'<rect x="{hx0-70:.1f}" y="{hy+hh*0.28:.1f}" width="76" height="{hh*0.16:.1f}" rx="6" fill="{mat("steel")[4]}" opacity=".6"/>')
    a.add(f'<rect x="{hx0-126:.1f}" y="{hy+hh*0.38:.1f}" width="60" height="{hh*0.24:.1f}" rx="4" fill="{mat("steel")[2]}"/>')
    # bit case below
    x, y, w, h = CX - 330, 430, 660, 300
    box3d(a, x, y, w, h, 44, case, rx=20)
    a.add(f'<rect x="{x+20:.1f}" y="{y+20:.1f}" width="{w-40:.1f}" height="{h-40:.1f}" rx="12" fill="{mat("plastic_bk")[2]}"/>')
    for r_ in range(2):
        for c_ in range(8):
            bx = x + 52 + c_ * (w - 104) / 7.0
            by = y + 56 + r_ * 112
            a.add(f'<rect x="{bx-13:.1f}" y="{by:.1f}" width="26" height="76" rx="7" fill="#07090c" opacity=".6"/>')
            a.add(f'<rect x="{bx-9:.1f}" y="{by+8:.1f}" width="18" height="58" rx="4" fill="{mat("steel")[2]}"/>')
            a.add(f'<rect x="{bx-9:.1f}" y="{by+8:.1f}" width="6" height="58" fill="{mat("steel")[4]}" opacity=".62"/>')
            a.add(f'<rect x="{bx-6:.1f}" y="{by+50:.1f}" width="12" height="16" rx="2" fill="{mat("anod_black")[2]}"/>')
    spec_sheen(a, x + 18, y + 14, w * 0.24, h - 28, rx=14, op=0.20)

def f_silicone_kit(a: Art, o: dict) -> None:
    """Two-part platinum-cure silicone: a pair of bottles plus a cured pad."""
    ground(a, CX, 812, 300, 42)
    for i, (sx, cm) in enumerate(((CX - 170, mat("plastic_wh")), (CX + 60, mat("silicone")))):
        box3d(a, sx - 96, 330, 192, 420, 52, cm, rx=26)
        a.add(f'<rect x="{sx-96:.1f}" y="{330:.1f}" width="192" height="96" rx="26" fill="{cm[4]}" opacity=".28"/>')
        a.add(f'<rect x="{sx-52:.1f}" y="{262:.1f}" width="104" height="74" rx="12" fill="{mat("anod_black")[2]}"/>')
        a.add(f'<rect x="{sx-52:.1f}" y="{262:.1f}" width="104" height="22" rx="10" fill="{mat("anod_black")[4]}" opacity=".25"/>')
        a.add(f'<rect x="{sx-70:.1f}" y="{470:.1f}" width="140" height="150" rx="10" fill="#ffffff" opacity=".82"/>')
        a.add(f'<text x="{sx:.1f}" y="{554:.1f}" text-anchor="middle" font-family="Helvetica,Arial,sans-serif" '
              f'font-size="64" font-weight="700" fill="#1d1d1f" fill-opacity=".72">{"AB"[i]}</text>')
    pm = mat("silicone")
    a.add(f'<ellipse cx="{CX-250:.1f}" cy="756" rx="130" ry="46" fill="{pm[2]}"/>')
    a.add(f'<ellipse cx="{CX-250:.1f}" cy="744" rx="130" ry="46" fill="{pm[3]}"/>')
    a.add(f'<ellipse cx="{CX-286:.1f}" cy="730" rx="46" ry="16" fill="#fff" opacity=".35"/>')


def f_filament(a: Art, o: dict) -> None:
    """Filament spool, three-quarter, with the wound face visible."""
    col = mat(o.get("color", "plastic_wh"))
    R = 300.0
    ground(a, CX, 830, 280, 42)
    sp = mat("plastic_bk")
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R:.1f}" fill="{sp[1]}"/>')
    fg = a.rad([(0, col[4], None), (0.42, col[3], None), (1, col[1], None)], cx=0.36, cy=0.30, r=0.84, tag="fil")
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R*0.86:.1f}" fill="url(#{fg})"/>')
    for i in range(26):
        rr = R * 0.40 + i * (R * 0.46) / 25
        a.add(f'<circle cx="{CX:.1f}" cy="500" r="{rr:.1f}" fill="none" stroke="{col[0]}" stroke-opacity=".18" stroke-width="1.6"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R*0.40:.1f}" fill="{sp[2]}"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R*0.16:.1f}" fill="#0a0d11"/>')
    for i in range(6):
        th = 2 * math.pi * i / 6 + 0.4
        a.add(f'<ellipse cx="{CX + R*0.28*math.cos(th):.1f}" cy="{500 + R*0.28*math.sin(th):.1f}" rx="{R*0.08:.1f}" ry="{R*0.08:.1f}" fill="#0a0d11" opacity=".45"/>')
    a.add(f'<path d="M {CX+R*0.80:.1f} 470 C {CX+R*1.06:.1f} 500 {CX+R*1.02:.1f} 620 {CX+R*0.74:.1f} 690" fill="none" stroke="{col[2]}" stroke-width="11" stroke-linecap="round"/>')
    spec_sheen(a, CX - R, 260, R * 0.62, R * 1.9, rx=R * 0.3, op=0.16, angle=-18)


def f_battery(a: Art, o: dict) -> None:
    """Li-ion pack in a shrink-wrapped brick with an XT60 and a balance tap."""
    m = mat(o.get("body", "anod_blue"))
    w, h = 560.0, 300.0
    x, y = CX - w / 2, 500 - h / 2
    ground(a, CX, y + h + 42, w * 0.50, 32)
    box3d(a, x, y, w, h, 84, m, rx=16)
    for i in range(4):
        a.add(f'<rect x="{x+18:.1f}" y="{y+22+i*(h-44)/3.6:.1f}" width="{w-36:.1f}" height="{(h-44)/5.2:.1f}" rx="10" fill="#000" opacity=".13"/>')
    a.add(f'<rect x="{x+w*0.60:.1f}" y="{y+h*0.30:.1f}" width="{w*0.30:.1f}" height="{h*0.40:.1f}" rx="8" fill="#ffffff" opacity=".84"/>')
    a.add(f'<rect x="{x+26:.1f}" y="{y+h*0.36:.1f}" width="72" height="52" rx="8" fill="{mat("anod_black")[2]}"/>')
    a.add(f'<circle cx="{x+46:.1f}" cy="{y+h*0.36+26:.1f}" r="13" fill="{mat("copper")[3]}"/>')
    a.add(f'<circle cx="{x+80:.1f}" cy="{y+h*0.36+26:.1f}" r="13" fill="{mat("copper")[3]}"/>')
    cable(a, [(x + 24, y + h * 0.62), (x - 84, y + h * 0.80), (x - 120, y + h + 30)], 13)
    spec_sheen(a, x + 14, y + 12, w * 0.24, h - 24, rx=12, op=0.18)




def f_hand(a: Art, o: dict) -> None:
    """Tendon-driven dexterous hand: palm, four fingers, opposed thumb."""
    m = mat(o.get("body", "plastic_wh"))
    jm = mat("anod_black")
    ground(a, CX, 876, 235, 40)
    box3d(a, CX - 116, 706, 232, 146, 58, jm, rx=24)
    for i in range(5):
        a.add(f'<rect x="{CX-94+i*39:.1f}" y="{722:.1f}" width="24" height="114" rx="8" fill="{jm[4]}" opacity=".16"/>')
    # palm — drawn before the thumb so the thumb root sits on top of it
    box3d(a, CX - 146, 486, 292, 226, 72, m, rx=44)

    def finger(fx, base, lengths, w0, lean):
        a.add(f'<g transform="rotate({lean:.1f} {fx:.1f} {base:.1f})">')
        top = base
        for j, L in enumerate(lengths):
            ww = w0 * (1.0 - j * 0.11)
            top -= L
            box3d(a, fx - ww / 2, top, ww, L, 30, m, rx=ww * 0.44)
            # knuckle: a soft shaded band, not a dot
            a.add(f'<rect x="{fx-ww/2:.1f}" y="{top+L-11:.1f}" width="{ww:.1f}" height="16" rx="8" fill="{jm[3]}" opacity=".55"/>')
            a.add(f'<circle cx="{fx-ww*0.30:.1f}" cy="{top+L-3:.1f}" r="{ww*0.10:.1f}" fill="{jm[1]}" opacity=".8"/>')
            top -= 9
        # fingertip pad
        a.add(f'<ellipse cx="{fx:.1f}" cy="{top+16:.1f}" rx="{w0*0.34:.1f}" ry="{w0*0.22:.1f}" fill="{mat("silicone")[4]}" opacity=".55"/>')
        a.add("</g>")

    for i, (dxp, lean) in enumerate(((-94, -7.0), (-31, -2.2), (31, 2.2), (94, 7.0))):
        finger(CX + dxp, 492, [(86, 72, 56), (96, 80, 60), (92, 76, 58), (76, 64, 50)][i], 56, lean)
    # opposed thumb, hinged off the palm's lower-left corner
    a.add(f'<g transform="rotate(-52 {CX-132:.1f} 660)">')
    a.add(f'<circle cx="{CX-132:.1f}" cy="660" r="30" fill="{jm[2]}"/>')
    box3d(a, CX - 165, 548, 66, 116, 40, m, rx=30)
    a.add(f'<rect x="{CX-165:.1f}" y="{653:.1f}" width="66" height="16" rx="8" fill="{jm[3]}" opacity=".55"/>')
    box3d(a, CX - 161, 452, 58, 92, 36, m, rx=27)
    a.add(f'<rect x="{CX-161:.1f}" y="{533:.1f}" width="58" height="15" rx="7" fill="{jm[3]}" opacity=".55"/>')
    a.add(f'<ellipse cx="{CX-132:.1f}" cy="{466:.1f}" rx="20" ry="13" fill="{mat("silicone")[4]}" opacity=".55"/>')
    a.add("</g>")
    a.add(f'<rect x="{CX-104:.1f}" y="{522:.1f}" width="208" height="146" rx="26" fill="{m[1]}" opacity=".38"/>')
    spec_sheen(a, CX - 136, 500, 74, 198, rx=34, op=0.26)

def f_mabel(a: Art, o: dict) -> None:
    """MABEL: swerve base, lift column, torso, two arms with hands, and a head.

    Drawn flat-with-shading rather than isometric — at catalogue size the extra
    faces of a box read as wedges hanging off the silhouette, not as depth."""
    body = mat("plastic_wh")
    dark = mat("anod_black")
    alu = mat("alu_dark")
    joint = mat("anod_red")

    def panel(x, y, w, h, m, rx, sheen=True):
        g = a.lin([(0.0, m[4], None), (0.22, m[3], None), (0.55, m[2], None), (1.0, m[1], None)],
                  0, 0, 1, 0.55, tag="pn")
        a.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="{rx:.1f}" fill="url(#{g})"/>')
        if sheen:
            a.add(f'<rect x="{x+w*0.06:.1f}" y="{y+h*0.05:.1f}" width="{w*0.20:.1f}" '
                  f'height="{h*0.90:.1f}" rx="{min(rx, w*0.10):.1f}" fill="#fff" opacity=".26"/>')

    ground(a, CX, 918, 262, 40)

    # --- base: dark chassis on two visible swerve wheels -------------------
    for wx in (CX - 132, CX + 132):
        a.add(f'<ellipse cx="{wx:.1f}" cy="886" rx="52" ry="30" fill="{mat("rubber")[1]}"/>')
        a.add(f'<ellipse cx="{wx:.1f}" cy="878" rx="52" ry="30" fill="{mat("rubber")[3]}"/>')
        a.add(f'<ellipse cx="{wx:.1f}" cy="876" rx="20" ry="11" fill="{alu[3]}"/>')
    panel(CX - 196, 792, 392, 76, dark, 26)
    a.add(f'<rect x="{CX-196:.1f}" y="836" width="392" height="32" rx="16" fill="#000" opacity=".22"/>')

    # --- lift column, three stages ----------------------------------------
    panel(CX - 46, 566, 92, 240, alu, 12)
    panel(CX - 35, 474, 70, 110, mat("alu"), 10)

    # --- torso ------------------------------------------------------------
    panel(CX - 136, 296, 272, 216, body, 46)
    a.add(f'<rect x="{CX-99:.1f}" y="334" width="198" height="140" rx="20" fill="{mat("glass")[0]}"/>')
    a.add(f'<rect x="{CX-99:.1f}" y="334" width="198" height="48" rx="20" fill="#fff" opacity=".13"/>')

    # --- arms: shoulder disc, upper arm, elbow, forearm, hand -------------
    for sd in (-1, 1):
        sx = CX + sd * 152
        a.add(f'<circle cx="{sx:.1f}" cy="342" r="40" fill="{alu[2]}"/>')
        a.add(f'<circle cx="{sx:.1f}" cy="342" r="38" fill="none" stroke="{alu[4]}" stroke-opacity=".4" stroke-width="2"/>')
        a.add(f'<circle cx="{sx:.1f}" cy="342" r="19" fill="{joint[2]}"/>')
        ux = sx + sd * 20
        a.add(f'<g transform="rotate({sd*13} {sx:.1f} 342)">')
        panel(ux - 27, 342, 54, 146, body, 26)
        a.add("</g>")
        ex = sx + sd * 52
        a.add(f'<circle cx="{ex:.1f}" cy="498" r="28" fill="{alu[2]}"/>')
        a.add(f'<circle cx="{ex:.1f}" cy="498" r="13" fill="{joint[2]}"/>')
        a.add(f'<g transform="rotate({sd*-8} {ex:.1f} 498)">')
        panel(ex - 23, 498, 46, 132, body, 22)
        a.add("</g>")
        hx = ex + sd * 4
        panel(hx - 25, 626, 50, 46, body, 16)
        for f_ in range(3):
            a.add(f'<rect x="{hx-19+f_*15:.1f}" y="668" width="10" height="40" rx="5" fill="{body[2]}"/>')
            a.add(f'<rect x="{hx-19+f_*15:.1f}" y="668" width="3.4" height="40" rx="1.7" fill="#fff" opacity=".4"/>')
        a.add(f'<rect x="{hx + sd*24 - 6:.1f}" y="654" width="12" height="34" rx="6" fill="{body[2]}"/>')

    # --- neck and head ----------------------------------------------------
    panel(CX - 23, 250, 46, 58, alu, 10)
    panel(CX - 92, 156, 184, 100, dark, 34, sheen=False)
    a.add(f'<rect x="{CX-92:.1f}" y="156" width="184" height="38" rx="30" fill="#fff" opacity=".10"/>')
    for ex_ in (CX - 41, CX + 41):
        a.add(f'<rect x="{ex_-30:.1f}" y="182" width="60" height="46" rx="15" fill="#06090c"/>')
        gl = a.rad([(0, "#7cd4ff", 0.98), (0.45, "#2f9fe0", 0.6), (1, "#2f9fe0", 0.0)], tag="eye")
        a.add(f'<ellipse cx="{ex_:.1f}" cy="205" rx="21" ry="14" fill="url(#{gl})"/>')
        a.add(f'<ellipse cx="{ex_-6:.1f}" cy="199" rx="7" ry="4" fill="#fff" opacity=".7"/>')
    _lens(a, CX, 152, 15)

def f_gearbox(a: Art, o: dict) -> None:
    """Planetary / harmonic gearbox — exposed ring gear and carrier."""
    m = mat(o.get("body", "steel"))
    R = 300.0
    ground(a, CX, 830, 250, 38)
    n = 42
    og = a.rad([(0, m[4], None), (0.42, m[3], None), (1, m[1], None)], cx=0.36, cy=0.30, r=0.84, tag="gb")
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R:.1f}" fill="url(#{og})"/>')
    for i in range(n):
        th = 2 * math.pi * i / n
        x1, y1 = CX + R * 0.90 * math.cos(th), 500 + R * 0.90 * math.sin(th)
        x2, y2 = CX + R * math.cos(th), 500 + R * math.sin(th)
        a.add(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="{m[0]}" stroke-opacity=".45" stroke-width="9"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R*0.70:.1f}" fill="{m[1]}" opacity=".5"/>')
    for i in range(3):
        th = 2 * math.pi * i / 3 - math.pi / 2
        px, py = CX + R * 0.40 * math.cos(th), 500 + R * 0.40 * math.sin(th)
        pg = a.rad([(0, m[4], None), (0.5, m[3], None), (1, m[1], None)], cx=0.36, cy=0.32, r=0.8, tag="pl")
        a.add(f'<circle cx="{px:.1f}" cy="{py:.1f}" r="{R*0.24:.1f}" fill="url(#{pg})"/>')
        for k in range(18):
            t2 = 2 * math.pi * k / 18
            a.add(f'<line x1="{px + R*0.215*math.cos(t2):.1f}" y1="{py + R*0.215*math.sin(t2):.1f}" '
                  f'x2="{px + R*0.24*math.cos(t2):.1f}" y2="{py + R*0.24*math.sin(t2):.1f}" stroke="{m[0]}" stroke-opacity=".5" stroke-width="6"/>')
        a.add(f'<circle cx="{px:.1f}" cy="{py:.1f}" r="{R*0.07:.1f}" fill="#0a0d11" opacity=".8"/>')
    sg = a.rad([(0, m[4], None), (0.5, m[3], None), (1, m[1], None)], cx=0.36, cy=0.32, r=0.8, tag="sun")
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R*0.17:.1f}" fill="url(#{sg})"/>')
    a.add(f'<circle cx="{CX:.1f}" cy="500" r="{R*0.07:.1f}" fill="#0a0d11" opacity=".85"/>')


FAMILIES = {
    "joint_module": f_joint_module,
    "harmonic_joint": f_harmonic_joint,
    "pancake": f_pancake,
    "micro_motor": f_micro_motor,
    "bus_servo": f_bus_servo,
    "stepper": f_stepper,
    "lift_column": f_lift_column,
    "swerve": f_swerve,
    "wheel": f_wheel,
    "extrusion": f_extrusion,
    "fastener_set": f_fastener_set,
    "bearing": f_bearing,
    "plate": f_plate,
    "pcb": f_pcb,
    "depth_camera": f_depth_camera,
    "cam_module": f_cam_module,
    "ego_camera": f_ego_camera,
    "lidar": f_lidar,
    "imu": f_imu,
    "compute": f_compute,
    "switch": f_switch,
    "cable_coil": f_cable_coil,
    "tool_kit": f_tool_kit,
    "silicone_kit": f_silicone_kit,
    "filament": f_filament,
    "battery": f_battery,
    "hand": f_hand,
    "mabel": f_mabel,
    "gearbox": f_gearbox,
}


def render(pid: str, family: str, title: str, opts: dict | None = None) -> str:
    a = Art(pid)
    fn = FAMILIES.get(family)
    if fn is None:
        raise KeyError(f"unknown art family: {family!r}")
    fn(a, opts or {})
    return a.render(title)
